### ISSUE TITLE
Allow user-specified identifiers at export tasks

### ISSUE THREAD

**Issue by KostasPatroumpas** [SLIPO-EU/workbench#14]
Once a user submits an export task (i.e., transforming an RDF resource into CSV or SHAPEFILE format), it is not possible to utilize the same resource in another export, e.g., in case this task has failed or the user wishes to get the data in another format. Currently, the application issues an error like "Workflow already exists".

**Comment by drmalex07** [comment]
Currently, we have an application-level constraint that every pair of (process-name, user-id) is unique.
Since the process-name (in the case of an export) is based only on the resource name ([here](https://github.com/SLIPO-EU/workbench/blob/master/webapp/src/main/java/eu/slipo/workbench/web/controller/action/ResourceController.java#L145)), an attempt to create another process will fail.

Maybe we should name the exporting process to something based on the pair (resource-name, export-timestamp). It is kind of heavy in terms of performance (since the same resource will always provide the same export), but is acceptable for now.
